"""rabbitkit — Production-grade RabbitMQ toolkit."""

from rabbitkit import experimental
from rabbitkit._version import __version__
from rabbitkit.async_.batch import AsyncBatchPublisher
from rabbitkit.async_.broker import AsyncBroker
from rabbitkit.asyncapi import AsyncAPIGeneratorConfig, generate_asyncapi_doc, generate_asyncapi_json
from rabbitkit.concurrency import AsyncWorkerPool, SyncWorkerPool
from rabbitkit.core.app import AppState, RabbitApp
from rabbitkit.core.bulk import (
    BulkPublishError,
    BulkPublishItem,
    BulkPublishOptions,
    BulkPublishResult,
    PublishPreparer,
)
from rabbitkit.core.config import (
    RETRY_DISABLED,
    BackpressureConfig,
    BatchAckConfig,
    BatchPublishConfig,
    CompressionConfig,
    ConnectionConfig,
    ConsumerConfig,
    DeduplicationConfig,
    HealthCheckConfig,
    MetricsConfig,
    PoolConfig,
    PublisherConfig,
    RabbitConfig,
    RetryConfig,
    RetryDisabled,
    RetryHandoffConfig,
    SafetyConfig,
    SecurityConfig,
    SocketConfig,
    SSLConfig,
    WorkerConfig,
)
from rabbitkit.core.errors import (
    BackpressureError,
    BrokerNotStartedError,
    ConfigurationError,
    ConfigValidationError,
    MessageTooLargeError,
    MissingDependencyError,
    SettlementError,
    TopologyValidationError,
    UnsafeTopologyError,
)
from rabbitkit.core.logging import DEFAULT_REDACT_KEYS, LoggingConfig, configure_structlog
from rabbitkit.core.message import AckMessage, NackMessage, RabbitMessage, RejectMessage
from rabbitkit.core.profiles import (
    PolicyTemplate,
    PreflightCheck,
    PreflightReport,
    ProfileViolation,
    apply_profile,
    critical_config,
    policy_templates,
    preflight,
    standard_config,
    validate_profile,
)
from rabbitkit.core.retry_handoff import RetryHandoffTracker
from rabbitkit.core.router import RabbitRouter
from rabbitkit.core.sanitizer import ErrorSanitizer, SanitizedError
from rabbitkit.core.settlement import (
    ContradictorySettlementError,
    CoordinatorError,
    LedgerFullError,
    SettlementCommand,
    SettlementCoordinator,
    SettlementItem,
    SettlementReport,
    SettlementReportError,
    StaleGenerationError,
    UnknownDeliveryError,
)
from rabbitkit.core.topology import RabbitExchange, RabbitQueue
from rabbitkit.core.types import (
    AckPolicy,
    BulkPublishStatus,
    ClassifiedError,
    DeduplicationMarkPolicy,
    DeliveryState,
    ErrorSeverity,
    ExchangeType,
    FlushReason,
    HandoffState,
    MessageEnvelope,
    PreflightStatus,
    PublishOutcome,
    PublishStatus,
    QueueType,
    RejectWithoutDLXPolicy,
    ReliabilityProfile,
    SettlementAction,
    SettlementItemStatus,
    TopologyMode,
)
from rabbitkit.di import Context, ContextRepo, Depends, DIResolver, Header, Path
from rabbitkit.di.resolver import DependencyScope
from rabbitkit.dlq import DLQInspector, ReplayResult
from rabbitkit.fastapi import rabbitkit_lifespan
from rabbitkit.health import (
    AsyncHealthWatcher,
    BrokerHealthResult,
    HealthStatus,
    HealthWatcher,
    broker_health_check,
    broker_health_check_async,
    broker_liveness,
    broker_liveness_async,
    broker_readiness,
    broker_readiness_async,
)
from rabbitkit.highload.backpressure import FlowController
from rabbitkit.highload.batch import (
    BatchAcker,
    BatchClosedError,
    BatchFlushError,
    BatchPublisher,
    ChannelMismatchError,
    CoalescingAcker,
    CoalescingAckerGroup,
    CoalescingFlushReport,
    FlushItem,
    FlushReport,
    GroupFlushReport,
)
from rabbitkit.management import ManagementConfig, RabbitManagementClient
from rabbitkit.middleware.circuit_breaker import CircuitBreakerMiddleware, CircuitBreakerOpenError
from rabbitkit.middleware.deduplication import DeduplicationMiddleware
from rabbitkit.middleware.metrics import (
    MetricsCollector,
    MetricsMiddleware,
    PrometheusCollector,
    metrics_app,
    start_metrics_server,
)
from rabbitkit.middleware.otel import OTelTracingMiddleware
from rabbitkit.middleware.rate_limit import RateLimitConfig, RateLimitMiddleware
from rabbitkit.queue_metrics import QueueMetricsPoller
from rabbitkit.serialization.pipeline import (
    DataclassDecoder,
    JsonParser,
    MessageDecoder,
    MessageParser,
    PydanticDecoder,
    RawDecoder,
    SerializationPipeline,
)
from rabbitkit.sync.batch import SyncBatchPublisher
from rabbitkit.sync.broker import SyncBroker

__all__ = [
    "DEFAULT_REDACT_KEYS",
    "RETRY_DISABLED",
    "AckMessage",
    "AckPolicy",
    "AppState",
    "AsyncAPIGeneratorConfig",
    "AsyncBatchPublisher",
    "AsyncBroker",
    "AsyncHealthWatcher",
    "AsyncWorkerPool",
    "BackpressureConfig",
    "BackpressureError",
    "BatchAckConfig",
    "BatchAcker",
    "BatchClosedError",
    "BatchFlushError",
    "BatchPublishConfig",
    "BatchPublisher",
    "BrokerHealthResult",
    "BrokerNotStartedError",
    "BulkPublishError",
    "BulkPublishItem",
    "BulkPublishOptions",
    "BulkPublishResult",
    "BulkPublishStatus",
    "ChannelMismatchError",
    "CircuitBreakerMiddleware",
    "CircuitBreakerOpenError",
    "ClassifiedError",
    "CoalescingAcker",
    "CoalescingAckerGroup",
    "CoalescingFlushReport",
    "CompressionConfig",
    "ConfigValidationError",
    "ConfigurationError",
    "ConnectionConfig",
    "ConsumerConfig",
    "Context",
    "ContextRepo",
    "ContradictorySettlementError",
    "CoordinatorError",
    "DIResolver",
    "DLQInspector",
    "DataclassDecoder",
    "DeduplicationConfig",
    "DeduplicationMarkPolicy",
    "DeduplicationMiddleware",
    "DeliveryState",
    "DependencyScope",
    "Depends",
    "ErrorSanitizer",
    "ErrorSeverity",
    "ExchangeType",
    "FlowController",
    "FlushItem",
    "FlushReason",
    "FlushReport",
    "GroupFlushReport",
    "HandoffState",
    "Header",
    "HealthCheckConfig",
    "HealthStatus",
    "HealthWatcher",
    "JsonParser",
    "LedgerFullError",
    "LoggingConfig",
    "ManagementConfig",
    "MessageDecoder",
    "MessageEnvelope",
    "MessageParser",
    "MessageTooLargeError",
    "MetricsCollector",
    "MetricsConfig",
    "MetricsMiddleware",
    "MissingDependencyError",
    "NackMessage",
    "OTelTracingMiddleware",
    "Path",
    "PolicyTemplate",
    "PoolConfig",
    "PreflightCheck",
    "PreflightReport",
    "PreflightStatus",
    "ProfileViolation",
    "PrometheusCollector",
    "PublishOutcome",
    "PublishPreparer",
    "PublishStatus",
    "PublisherConfig",
    "PydanticDecoder",
    "QueueMetricsPoller",
    "QueueType",
    "RabbitApp",
    "RabbitConfig",
    "RabbitExchange",
    "RabbitManagementClient",
    "RabbitMessage",
    "RabbitQueue",
    "RabbitRouter",
    "RateLimitConfig",
    "RateLimitMiddleware",
    "RawDecoder",
    "RejectMessage",
    "RejectWithoutDLXPolicy",
    "ReliabilityProfile",
    "ReplayResult",
    "RetryConfig",
    "RetryDisabled",
    "RetryHandoffConfig",
    "RetryHandoffTracker",
    "SSLConfig",
    "SafetyConfig",
    "SanitizedError",
    "SecurityConfig",
    "SerializationPipeline",
    "SettlementAction",
    "SettlementCommand",
    "SettlementCoordinator",
    "SettlementError",
    "SettlementItem",
    "SettlementItemStatus",
    "SettlementReport",
    "SettlementReportError",
    "SocketConfig",
    "StaleGenerationError",
    "SyncBatchPublisher",
    "SyncBroker",
    "SyncWorkerPool",
    "TopologyMode",
    "TopologyValidationError",
    "UnknownDeliveryError",
    "UnsafeTopologyError",
    "WorkerConfig",
    "__version__",
    "apply_profile",
    "broker_health_check",
    "broker_health_check_async",
    "broker_liveness",
    "broker_liveness_async",
    "broker_readiness",
    "broker_readiness_async",
    "configure_structlog",
    "critical_config",
    "experimental",
    "generate_asyncapi_doc",
    "generate_asyncapi_json",
    "metrics_app",
    "policy_templates",
    "preflight",
    "rabbitkit_lifespan",
    "standard_config",
    "start_metrics_server",
    "validate_profile",
]
